from waflib.Task import Task
import subprocess

class content(Task):
    def run(self):
        template = self.inputs[0].read()
        for p in self.inputs[1:]:
            template = template.replace('[[%s]]'%p.name, p.read())
        xxd=subprocess.Popen(['xxd', '-i'], stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
        try:
            out, err = xxd.communicate(input=template)
            self.outputs[0].write('unsigned char content_h[] = {\n%s\n};\n'%out+
                                  'unsigned int content_h_len = %d;\n'%(out.count(',')+1))
            return 0
        except Exception as e:
            print e
            return 1

def build(bld):
    content_h = content(env=bld.env)
    content_h.set_inputs([
        bld.path.find_resource('html/content.tmpl'),
        bld.path.find_resource('js/main.js'),
        bld.path.find_resource('js/term.js'),
        bld.path.find_resource('css/content.css')
    ])
    content_h.set_outputs([bld.path.find_or_declare('include/content.h')])
    bld.add_to_group(content_h)
